# docker compose up -d
version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: smunity
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root1234!
      MYSQL_DATABASE: smunity
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
