insert into core_standard (year_id, category, total)
values (1, 'CULTURE', 36),
       (1, 'MAJOR_ADVANCED', 15),
       (1, 'MAJOR_OPTIONAL', 45),
       (2, 'CULTURE', 33),
       (2, 'MAJOR_ADVANCED', 15),
       (2, 'MAJOR_OPTIONAL', 45),
       (3, 'CULTURE', 33),
       (3, 'MAJOR_ADVANCED', 15),
       (3, 'MAJOR_OPTIONAL', 45),
       (4, 'CULTURE', 33),
       (4, 'MAJOR_ADVANCED', 15),
       (4, 'MAJOR_OPTIONAL', 45),
       (5, 'CULTURE', 33),
       (5, 'MAJOR_ADVANCED', 15),
       (5, 'MAJOR_OPTIONAL', 45),
       (6, 'CULTURE', 33),
       (6, 'MAJOR_ADVANCED', 15),
       (6, 'MAJOR_OPTIONAL', 45),
       (7, 'CULTURE', 33),
       (7, 'MAJOR_ADVANCED', 15),
       (7, 'MAJOR_OPTIONAL', 60);
